/**
 * Onboarding stall detection — weekly Tuesday 09:00 UTC.
 * Wave V / V4.
 *
 * Scans `cd_onboarding_snapshots` (the Turso mirror of CD's submissions,
 * populated by pull-onboarding-from-portal every 6h). Flags any onboarding
 * where:
 *   - status is not 'submitted', AND
 *   - cd_updated_at is older than 5 days (no activity), AND
 *   - completion_percent < 100
 *
 * For each stall, creates an Asana task assigned to the client's AM,
 * dropped into the AM's project if we can resolve one. Idempotent: skips
 * any client that already has an open stall task in the last 7 days
 * (tracked in a new `onboarding_stall_tasks` table).
 */
import { db } from '../queries/base.js';
import { createPrivateAsanaTask } from '../asana/tasks.js';
import { getClientAM, resolveClientAMGid } from '../asana/assignee.js';
import { consoleLog } from '../monitors/base.js';

const LOG_SOURCE = 'onboarding-stall';

export interface OnboardingStallRow {
  clientId: number;
  clientName: string;
  daysSinceActivity: number;
  completionPercent: number;
  am: string;
  asanaTaskGid: string | null;
}

export interface OnboardingStallResult {
  candidates: number;
  tasksCreated: number;
  skipped: number;
  durationMs: number;
  rows: OnboardingStallRow[];
}

async function ensureSchema(): Promise<void> {
  await db.execute(`
    CREATE TABLE IF NOT EXISTS onboarding_stall_tasks (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      client_id INTEGER NOT NULL,
      client_name TEXT NOT NULL,
      asana_task_gid TEXT,
      days_since_activity INTEGER NOT NULL,
      created_at TEXT NOT NULL
    )
  `);
}

async function recentlyFlagged(clientId: number, daysBack: number): Promise<boolean> {
  const r = await db.execute({
    sql: `SELECT 1 FROM onboarding_stall_tasks
          WHERE client_id = ? AND created_at >= date('now', ?)
          LIMIT 1`,
    args: [clientId, `-${daysBack} days`],
  });
  return r.rows.length > 0;
}

async function resolveAsanaProject(clientId: number): Promise<string | undefined> {
  const r = await db.execute({
    sql: `SELECT external_id FROM client_source_mappings
          WHERE client_id = ? AND source = 'asana' LIMIT 1`,
    args: [clientId],
  });
  const v = r.rows[0]?.external_id;
  return v ? String(v) : undefined;
}

export async function runOnboardingStallDetection(): Promise<OnboardingStallResult> {
  const start = Date.now();
  await ensureSchema();
  const nowIso = new Date().toISOString();

  // `julianday('now') - julianday(cd_updated_at)` is days as a real number.
  // Cast to int and filter > 5.
  const stalled = await db.execute(`
    SELECT s.client_id, c.name AS client_name,
           CAST(julianday('now') - julianday(s.cd_updated_at) AS INTEGER) AS days_idle,
           COALESCE(s.completion_percent, 0) AS pct
    FROM cd_onboarding_snapshots s
    JOIN clients c ON c.id = s.client_id
    WHERE s.status != 'submitted'
      AND COALESCE(s.completion_percent, 0) < 100
      AND julianday('now') - julianday(s.cd_updated_at) > 5
  `);

  const rows: OnboardingStallRow[] = [];
  let skipped = 0;
  let tasksCreated = 0;

  // Calculate the due date (3 working days from now) once
  const due = new Date();
  due.setDate(due.getDate() + 3);
  const dueOn = due.toISOString().slice(0, 10);

  for (const r of stalled.rows) {
    const clientId = Number(r.client_id);
    const clientName = String(r.client_name);
    const daysIdle = Number(r.days_idle);
    const pct = Number(r.pct);

    if (await recentlyFlagged(clientId, 7)) { skipped++; continue; }

    const am = (await getClientAM(clientName)) || 'Unassigned';
    const amGid = await resolveClientAMGid(clientName);
    let taskGid: string | null = null;

    if (amGid) {
      const projectGid = await resolveAsanaProject(clientId);
      const notes = [
        `Onboarding for ${clientName} has stalled.`,
        ``,
        `Last activity: ${daysIdle} days ago`,
        `Completion: ${pct}%`,
        ``,
        `Action: chase the client to finish their onboarding so kickoff isn't held up.`,
        ``,
        `(Auto-generated by VendoOS onboarding-stall cron.)`,
      ].join('\n');
      try {
        taskGid = await createPrivateAsanaTask({
          name: `Chase onboarding — ${clientName} (${daysIdle}d idle)`,
          assigneeGid: amGid,
          dueOn,
          notes,
          projects: projectGid ? [projectGid] : [],
        });
        tasksCreated++;
      } catch (err) {
        consoleLog(LOG_SOURCE, `Asana task create failed for ${clientName}: ${err instanceof Error ? err.message : err}`);
      }
    } else {
      consoleLog(LOG_SOURCE, `Skipping ${clientName} — no AM gid resolvable`);
    }

    await db.execute({
      sql: `INSERT INTO onboarding_stall_tasks
              (client_id, client_name, asana_task_gid, days_since_activity, created_at)
            VALUES (?, ?, ?, ?, ?)`,
      args: [clientId, clientName, taskGid, daysIdle, nowIso] as (string | number | null)[],
    });

    rows.push({ clientId, clientName, daysSinceActivity: daysIdle, completionPercent: pct, am, asanaTaskGid: taskGid });
  }

  return {
    candidates: rows.length + skipped,
    tasksCreated,
    skipped,
    durationMs: Date.now() - start,
    rows,
  };
}
