/**
 * Client Offboarding — access revocation, final invoice, data archive, learnings.
 *
 * Usage:
 *   npx tsx scripts/functions/client-offboarding.ts --start "Client Name" "reason"
 *   npx tsx scripts/functions/client-offboarding.ts --status
 */
import { config } from 'dotenv';
config({ path: '.env.local' });

import { getDb, initSchema, saveDb, closeDb, log, logError } from '../utils/db.js';
import { sendSlackAlert } from '../utils/slack-alert.js';

const ASANA_API_KEY = process.env.ASANA_API_KEY || '';
const ASANA_WORKSPACE_GID = process.env.ASANA_WORKSPACE_GID || '';
const ASANA_BASE_URL = 'https://app.asana.com/api/1.0';
const SLACK_SLT_WEBHOOK = process.env.SLACK_SLT_WEBHOOK_URL || '';

interface ChecklistItem { task: string; owner: string; status: 'pending' | 'done' }

function generateChecklist(): ChecklistItem[] {
  return [
    { task: 'Notify client of contract end and timeline', owner: 'AM', status: 'pending' },
    { task: 'Generate and send final invoice', owner: 'Sarah', status: 'pending' },
    { task: 'Revoke ad platform access (Google/Meta)', owner: 'Specialist', status: 'pending' },
    { task: 'Remove from Slack channel', owner: 'AM', status: 'pending' },
    { task: 'Archive Google Drive folder', owner: 'AM', status: 'pending' },
    { task: 'Close Asana project', owner: 'AM', status: 'pending' },
    { task: 'Update GHL contact status to churned', owner: 'AM', status: 'pending' },
    { task: 'Transfer any remaining assets to client', owner: 'Specialist', status: 'pending' },
    { task: 'Conduct exit interview / feedback call', owner: 'Founder', status: 'pending' },
    { task: 'Log learnings to decision journal', owner: 'Founder', status: 'pending' },
    { task: 'Remove from monthly reporting cycle', owner: 'AM', status: 'pending' },
    { task: 'Remove from daily brief', owner: 'System', status: 'pending' },
    { task: 'Archive client data (do not delete)', owner: 'System', status: 'pending' },
  ];
}

async function createAsanaOffboardingTasks(clientName: string, checklist: ChecklistItem[]): Promise<string | null> {
  if (!ASANA_API_KEY || !ASANA_WORKSPACE_GID) {
    log('CLIENT-OFFBOARD', 'Asana not configured — skipping task creation');
    return null;
  }

  try {
    // Create a parent task for the offboarding
    const parentRes = await fetch(`${ASANA_BASE_URL}/tasks`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${ASANA_API_KEY}`,
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        data: {
          name: `[OFFBOARD] ${clientName} — Offboarding Checklist`,
          notes: `Client offboarding checklist for ${clientName}.\nGenerated by Vendo OS.`,
          workspace: ASANA_WORKSPACE_GID,
        },
      }),
    });

    if (!parentRes.ok) {
      const body = await parentRes.text();
      logError('CLIENT-OFFBOARD', `Asana parent task failed: ${parentRes.status} ${body}`);
      return null;
    }

    const parentJson = await parentRes.json() as { data: { gid: string } };
    const parentGid = parentJson.data.gid;

    // Create subtasks for each checklist item
    for (const item of checklist) {
      await fetch(`${ASANA_BASE_URL}/tasks/${parentGid}/subtasks`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${ASANA_API_KEY}`,
          'Accept': 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          data: { name: `${item.task} (${item.owner})` },
        }),
      });
    }

    log('CLIENT-OFFBOARD', `Asana tasks created: parent ${parentGid} with ${checklist.length} subtasks`);
    return parentGid;
  } catch (err) {
    logError('CLIENT-OFFBOARD', 'Asana task creation error', err);
    return null;
  }
}

async function updateClientStatus(clientName: string): Promise<void> {
  const db = await getDb();
  db.run("UPDATE clients SET status = 'churned' WHERE name = ? OR display_name = ?", [clientName, clientName]);
  saveDb();
  log('CLIENT-OFFBOARD', `Client status updated to 'churned': ${clientName}`);
}

async function sendSltChurnNotification(clientName: string, reason: string): Promise<void> {
  // Estimate MRR impact from invoicing data
  const db = await getDb();
  let mrrEstimate = 0;
  const invoiceResult = db.exec(`
    SELECT ROUND(SUM(total) / COUNT(DISTINCT strftime('%Y-%m', date)), 0) as mrr
    FROM xero_invoices
    WHERE contact_name = ? AND type = 'ACCREC' AND status IN ('PAID', 'AUTHORISED')
  `, [clientName]);

  if (invoiceResult.length && invoiceResult[0].values.length && invoiceResult[0].values[0][0]) {
    mrrEstimate = invoiceResult[0].values[0][0] as number;
  }

  // Send to SLT webhook
  if (SLACK_SLT_WEBHOOK) {
    try {
      await fetch(SLACK_SLT_WEBHOOK, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text: `:rotating_light: *CLIENT CHURN — ${clientName}*\n` +
            `*Reason:* ${reason}\n` +
            `*Est. MRR Impact:* GBP ${mrrEstimate.toLocaleString()}\n` +
            `*Status:* Offboarding started\n` +
            `*Time:* ${new Date().toISOString()}`,
        }),
      });
      log('CLIENT-OFFBOARD', 'SLT Slack notification sent');
    } catch (err) {
      logError('CLIENT-OFFBOARD', 'SLT notification failed', err);
    }
  }

  // Also send to main Slack channel
  await sendSlackAlert(
    'client-offboard',
    `Client churn: ${clientName} — ${reason} (Est. MRR impact: GBP ${mrrEstimate.toLocaleString()})`,
    'error',
  );
}

async function startOffboarding(clientName: string, reason: string): Promise<void> {
  const db = await getDb();
  const now = new Date().toISOString();
  const checklist = generateChecklist();

  db.run(`
    INSERT INTO client_offboarding (client_name, reason, checklist, status, created_at, updated_at)
    VALUES (?, ?, ?, 'pending', ?, ?)
  `, [clientName, reason, JSON.stringify(checklist), now, now]);

  saveDb();
  log('CLIENT-OFFBOARD', `Offboarding started: ${clientName} — ${reason}`);
  log('CLIENT-OFFBOARD', `  ${checklist.length} checklist items`);

  // Create Asana offboarding task list
  await createAsanaOffboardingTasks(clientName, checklist);

  // Update client status to churned
  await updateClientStatus(clientName);

  // Send SLT notification with churn reason + MRR impact
  await sendSltChurnNotification(clientName, reason);

  console.log('\n  Immediate actions:');
  for (const item of checklist.slice(0, 3)) {
    console.log(`    [ ] ${item.task} (${item.owner})`);
  }
  console.log('');
}

async function showStatus(): Promise<void> {
  const db = await getDb();
  const result = db.exec(`
    SELECT client_name, reason, checklist, status, created_at
    FROM client_offboarding ORDER BY created_at DESC
  `);

  if (!result.length || !result[0].values.length) {
    log('CLIENT-OFFBOARD', 'No client offboardings');
    return;
  }

  console.log('\n=== Client Offboarding ===\n');
  for (const row of result[0].values) {
    const [name, reason, clJson, status, created] = row as string[];
    const checklist: ChecklistItem[] = JSON.parse(clJson);
    const done = checklist.filter((i) => i.status === 'done').length;
    console.log(`  ${name} — ${reason}`);
    console.log(`    Status: ${status} | Progress: ${done}/${checklist.length} | Started: ${created.split('T')[0]}`);
    console.log('');
  }
}

async function main() {
  await initSchema();
  if (process.argv.includes('--start')) {
    const idx = process.argv.indexOf('--start');
    const name = process.argv[idx + 1];
    const reason = process.argv[idx + 2] ?? 'contract end';
    if (!name) { logError('CLIENT-OFFBOARD', 'Usage: --start "Client" "reason"'); process.exit(1); }
    await startOffboarding(name, reason);
  } else { await showStatus(); }
  closeDb();
}

main().catch((err) => { logError('CLIENT-OFFBOARD', 'Failed', err); process.exit(1); });
